name: SimpleGamemode
version: 2.1
author: Maximilian1021
website: https://game-energy.de


main: me.maximilian1021.main.Main

commands:
  gm:
    description: Wechsel dein Gamemode
    usage: /<command>